import React from "react";
import type { Metadata } from "next";
import { geistSans, geistMono } from "#/app/fonts";
import "#/styles/globals.css";

export const metadata: Metadata = {
  title: "Google reCAPTCHA v3 Integration with Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
